# Generated by Django 3.1.1 on 2020-09-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
